- name: Installed the required packages
  hosts: webserver
  tasks:
    - name: Install the required packages
      yum: 
        name: "{{ ansible_local.custom.general.package }}"
        state: latest

    - name: Start the service
      service: 
        name: "{{ ansible_local.custom.general.package }}"
        state: "{{ ansible_local.custom.general.state }}"

