---
- hosts: all
  user: devops
  become: true
  vars:
    system_owner: systems@massive.org.au
  tasks:
    - template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
